name: Nightly Data Build

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 10.5.2
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Build core bundle
        run: pnpm build
      - name: Build schemas
        run: pnpm build:schemas
      - name: Build client configs
        run: POE_MCP_CLIENTS_ABS=$(pwd) pnpm build:clients
      - name: Build launcher scripts
        run: pnpm build:bin
      - name: Run ETL (full)
        run: pnpm etl:all
      - name: Validate dataset
        run: pnpm data:validate
      - name: Run tests
        run: bash -c "set -o pipefail && pnpm exec vitest run --reporter=basic | tee vitest-report.txt"
      - name: Upload latest dataset
        uses: actions/upload-artifact@v4
        with:
          name: data-latest
          path: data/latest
          if-no-files-found: error
      - name: Upload manifest
        uses: actions/upload-artifact@v4
        with:
          name: manifest
          path: manifest.json
          if-no-files-found: error
      - name: Upload client bundles
        uses: actions/upload-artifact@v4
        with:
          name: clients
          path: dist/clients
          if-no-files-found: error
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: dist/coverage
          if-no-files-found: warn
      - name: Upload vitest report
        uses: actions/upload-artifact@v4
        with:
          name: vitest-report
          path: vitest-report.txt
          if-no-files-found: warn
